// Color Palette
export const COLORS = {
  primary: '#2563eb',
  secondary: '#0f172a',
  accent: '#22c55e',
  gray: '#f3f4f6',
  darkGray: '#1f2937',
};

// Dummy Data
export const STATS = [
  { label: '10K+', value: 'Parking Spots' },
  { label: '5K+', value: 'Active Users' },
  { label: '20+', value: 'Cities' },
];

export const PARKING_SPOTS = [
  {
    id: 1,
    name: 'Downtown Premium Parking',
    type: 'paid',
    price: 50,
    priceType: 'hourly',
    available: 12,
    total: 45,
    rating: 4.8,
    reviews: 245,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6139,
    lng: 77.2090,
    address: 'Connaught Place, New Delhi',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Well-lit', 'Secure'],
  },
  {
    id: 2,
    name: 'Community Free Parking',
    type: 'free',
    price: 0,
    priceType: 'free',
    available: 8,
    total: 20,
    rating: 4.2,
    reviews: 120,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=400&h=300&fit=crop',
    lat: 28.6262,
    lng: 77.1778,
    address: 'Defence Colony, New Delhi',
    timings: '6 AM - 11 PM',
    cctv: false,
    verified: true,
    features: ['Open', 'Spacious'],
  },
  {
    id: 3,
    name: 'Business District Parking',
    type: 'paid',
    price: 150,
    priceType: 'daily',
    available: 25,
    total: 60,
    rating: 4.9,
    reviews: 425,
    image: 'https://images.unsplash.com/photo-1487015369519-3f2931fd45c3?w=400&h=300&fit=crop',
    lat: 28.5494,
    lng: 77.1621,
    address: 'Gurugram Tech Park',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Reserved spots', 'Indoor'],
  },
  {
    id: 4,
    name: 'Mall Parking Complex',
    type: 'paid',
    price: 30,
    priceType: 'hourly',
    available: 45,
    total: 120,
    rating: 4.6,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.5689,
    lng: 77.2194,
    address: 'DLF Mall, Saket, New Delhi',
    timings: '10 AM - 10 PM',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Multi-level', 'Valet'],
  },
  {
    id: 5,
    name: 'Airport Parking Plaza',
    type: 'paid',
    price: 200,
    priceType: 'daily',
    available: 78,
    total: 150,
    rating: 4.7,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.5562,
    lng: 77.1000,
    address: 'IGI Airport, New Delhi',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Shuttle service', 'Long-term'],
  },
  {
    id: 6,
    name: 'Residential Street Parking',
    type: 'free',
    price: 0,
    priceType: 'free',
    available: 15,
    total: 30,
    rating: 3.8,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=400&h=300&fit=crop',
    lat: 28.6353,
    lng: 77.2244,
    address: 'Karol Bagh, New Delhi',
    timings: '6 AM - 10 PM',
    cctv: false,
    verified: false,
    features: ['Street parking', 'Residential'],
  },
  {
    id: 7,
    name: 'Hospital Parking Lot',
    type: 'paid',
    price: 40,
    priceType: 'hourly',
    available: 22,
    total: 50,
    rating: 4.4,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.5672,
    lng: 77.2100,
    address: 'AIIMS Hospital, New Delhi',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Emergency access', 'Covered'],
  },
  {
    id: 8,
    name: 'Metro Station Parking',
    type: 'paid',
    price: 25,
    priceType: 'hourly',
    available: 35,
    total: 80,
    rating: 4.3,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6139,
    lng: 77.2090,
    address: 'Rajiv Chowk Metro Station',
    timings: '5 AM - 11 PM',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Metro access', 'Quick exit'],
  },
  {
    id: 9,
    name: 'University Campus Parking',
    type: 'paid',
    price: 20,
    priceType: 'hourly',
    available: 55,
    total: 100,
    rating: 4.5,
    reviews: 278,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=400&h=300&fit=crop',
    lat: 28.5406,
    lng: 77.1661,
    address: 'JNU Campus, New Delhi',
    timings: '6 AM - 8 PM',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Student discount', 'Large capacity'],
  },
  {
    id: 10,
    name: 'Market Area Parking',
    type: 'paid',
    price: 35,
    priceType: 'hourly',
    available: 18,
    total: 40,
    rating: 4.1,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6500,
    lng: 77.2300,
    address: 'Chandni Chowk Market, Delhi',
    timings: '8 AM - 9 PM',
    cctv: false,
    verified: true,
    features: ['Market access', 'Busy area'],
  },
  {
    id: 11,
    name: 'Office Complex Parking',
    type: 'paid',
    price: 60,
    priceType: 'hourly',
    available: 28,
    total: 70,
    rating: 4.7,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1487015369519-3f2931fd45c3?w=400&h=300&fit=crop',
    lat: 28.6294,
    lng: 77.0800,
    address: 'Cyber City, Gurugram',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Office access', 'Reserved'],
  },
  {
    id: 12,
    name: 'Stadium Parking Arena',
    type: 'paid',
    price: 100,
    priceType: 'daily',
    available: 120,
    total: 200,
    rating: 4.8,
    reviews: 445,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6139,
    lng: 77.2090,
    address: 'Jawaharlal Nehru Stadium',
    timings: 'Event hours',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Event parking', 'Large capacity'],
  },
  {
    id: 13,
    name: 'Restaurant Row Parking',
    type: 'paid',
    price: 45,
    priceType: 'hourly',
    available: 12,
    total: 25,
    rating: 4.2,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6289,
    lng: 77.2194,
    address: 'Khan Market, New Delhi',
    timings: '10 AM - 11 PM',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Restaurant access', 'Premium'],
  },
  {
    id: 14,
    name: 'Park & Ride Parking',
    type: 'paid',
    price: 80,
    priceType: 'daily',
    available: 65,
    total: 100,
    rating: 4.4,
    reviews: 267,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=400&h=300&fit=crop',
    lat: 28.7041,
    lng: 77.1025,
    address: 'ISBT Kashmere Gate',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Bus terminal', 'Long-term'],
  },
  {
    id: 15,
    name: 'Luxury Hotel Parking',
    type: 'paid',
    price: 120,
    priceType: 'daily',
    available: 8,
    total: 15,
    rating: 4.9,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6139,
    lng: 77.2090,
    address: 'The Imperial, Janpath',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Valet service', 'Luxury'],
  },
  {
    id: 16,
    name: 'Community Center Parking',
    type: 'free',
    price: 0,
    priceType: 'free',
    available: 20,
    total: 35,
    rating: 3.9,
    reviews: 87,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=400&h=300&fit=crop',
    lat: 28.6353,
    lng: 77.2244,
    address: 'RK Puram Community Center',
    timings: '6 AM - 10 PM',
    cctv: false,
    verified: false,
    features: ['Community access', 'Free parking'],
  },
  {
    id: 17,
    name: 'Tech Hub Parking',
    type: 'paid',
    price: 70,
    priceType: 'hourly',
    available: 42,
    total: 85,
    rating: 4.6,
    reviews: 334,
    image: 'https://images.unsplash.com/photo-1487015369519-3f2931fd45c3?w=400&h=300&fit=crop',
    lat: 28.4595,
    lng: 77.0266,
    address: 'Noida Tech Park',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Tech companies', 'Modern'],
  },
  {
    id: 18,
    name: 'Railway Station Parking',
    type: 'paid',
    price: 50,
    priceType: 'daily',
    available: 30,
    total: 60,
    rating: 4.0,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    lat: 28.6139,
    lng: 77.2090,
    address: 'New Delhi Railway Station',
    timings: '24/7',
    cctv: true,
    verified: true,
    features: ['CCTV', 'Rail access', 'Long-term'],
  },
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 1,
    name: 'Basic',
    price: 499,
    period: 'per month',
    benefits: [
      'Access to 100+ parking spots',
      '10% discount on bookings',
      'Priority booking',
      'Email support',
    ],
    popular: false,
  },
  {
    id: 2,
    name: 'Pro',
    price: 999,
    period: 'per month',
    benefits: [
      'Access to 500+ parking spots',
      '25% discount on bookings',
      'Priority support',
      'Reserved parking slots',
      'Free cancellations (2x/month)',
      'Exclusive daily deals',
    ],
    popular: true,
  },
  {
    id: 3,
    name: 'Business',
    price: 1999,
    period: 'per month',
    benefits: [
      'Unlimited parking access',
      '50% discount on bookings',
      '24/7 priority support',
      'Unlimited reserved slots',
      'Free cancellations',
      'Business reporting',
      'Dedicated account manager',
    ],
    popular: false,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Priyanshu Raj Chauhan',
    role: 'Business Manager',
    text: 'ParkEasy saved me hours every week. Finding parking in Delhi is now just 30 seconds!',
    rating: 5,
    avatar: '👨‍💼',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    role: 'Software Engineer',
    text: 'The app is incredibly intuitive. Worth every penny for the peace of mind.',
    rating: 5,
    avatar: '👩‍💻',
  },
  {
    id: 3,
    name: 'Arjun Patel',
    role: 'Entrepreneur',
    text: 'Great platform to rent out my parking. Making 3000+ every month!',
    rating: 5,
    avatar: '👨‍🏫',
  },
];

export const FAQ = [
  {
    id: 1,
    question: 'How do I book a parking spot?',
    answer: 'Simply search for parking in your area, select a spot, choose your duration, and pay. Your booking is confirmed instantly!',
  },
  {
    id: 2,
    question: 'Can I cancel my booking?',
    answer: 'Yes, you can cancel up to 30 minutes before your booking time with a full refund.',
  },
  {
    id: 3,
    question: 'How do I list my parking space?',
    answer: 'Go to the "List Your Space" section, add your parking details, photos, and pricing. We verify and approve within 24 hours.',
  },
  {
    id: 4,
    question: 'Is my payment secure?',
    answer: 'Yes, we use bank-level encryption and Razorpay for secure payments.',
  },
  {
    id: 5,
    question: 'What payment methods are accepted?',
    answer: 'We accept UPI, Credit/Debit cards, Net Banking, and Wallets.',
  },
  {
    id: 6,
    question: 'Is there 24/7 support?',
    answer: 'Yes, our support team is available 24/7 via chat, email, and phone.',
  },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Search',
    description: 'Find nearby parking with real-time availability',
    icon: '🔍',
  },
  {
    step: 2,
    title: 'Select',
    description: 'Choose your preferred spot and duration',
    icon: '✓',
  },
  {
    step: 3,
    title: 'Book',
    description: 'Reserve and pay securely in seconds',
    icon: '📱',
  },
  {
    step: 4,
    title: 'Park',
    description: 'Park your vehicle with peace of mind',
    icon: '🚗',
  },
];
